
replicaCount: 1

containerPort: 3000
healthcheck_url: "/healthcheck"

image:
  repository: gcavalcante8808/idwall
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: idwall.ts3corp.com.br
      paths:
      - /
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 32Mi
  requests:
    cpu: 100m
    memory: 32Mi

nodeSelector: {}

tolerations: []

affinity: {}

