version: "2"

services:
  challenge:
    image: idwall-challenge:latest
    build: .
    user: "65534"
    cap_drop:
    - ALL
    environment:
      NAME: "Gabriel Abdalla Cavalcante Silva"
    ports:
      - 3000:3000
