version: "2.2"

services:
  challenge:
    image: idwall-challenge:latest
    build: .
    user: "65534"
    healthcheck:
      test: ["CMD", "curl", "-f","http://localhost:3000/healthcheck"]
      interval: 60s
      timeout: 2s
      retries: 3
    cap_drop:
    - ALL
    environment:
      NAME: "Gabriel Abdalla Cavalcante Silva"
    ports:
      - 3000:3000
